# Generated by Django 2.2.7 on 2020-03-20 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_id', models.CharField(max_length=150, unique=True)),
                ('discount_name', models.CharField(max_length=150)),
                ('discount_percent', models.FloatField()),
                ('discount_amount', models.FloatField()),
                ('discount_torder', models.BooleanField()),
                ('discount_tuses', models.IntegerField()),
                ('discount_usespuser', models.IntegerField()),
            ],
            options={
                'db_table': 'nitro_discounts',
            },
        ),
        migrations.CreateModel(
            name='PaymentDataStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_ID', models.TextField()),
                ('payment_status', models.BooleanField()),
            ],
            options={
                'db_table': 'nitro_paymentdtstream',
            },
        ),
        migrations.CreateModel(
            name='POS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.CharField(max_length=3, unique=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('deploy_state', models.BooleanField()),
                ('wifinetwork', models.CharField(max_length=255, null=True)),
                ('wifiusername', models.CharField(max_length=255, null=True)),
                ('wifipassword', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'nitro_pos',
            },
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('volume', models.IntegerField()),
                ('volumeunits', models.IntegerField()),
                ('volumeunitprice', models.FloatField()),
            ],
            options={
                'db_table': 'nitro_sku',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nitro_profile',
            },
        ),
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_id', models.CharField(max_length=9, unique=True)),
                ('o_date', models.DateField()),
                ('o_time', models.DateTimeField()),
                ('ordervolume', models.IntegerField()),
                ('ordervalue', models.FloatField()),
                ('discount_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Discounts')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_id', to='main.POS')),
                ('payment_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_id', to='main.PaymentDataStream')),
                ('payment_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_status', to='main.PaymentDataStream')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_id', to='main.SKU')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cus_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nitro_orderlog',
            },
        ),
    ]
