# Generated by Django 2.2.7 on 2020-03-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='POS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.CharField(max_length=3)),
                ('location', models.TextField()),
                ('deploy_state', models.BooleanField()),
                ('wifinetwork', models.TextField()),
                ('wifiusername', models.TextField()),
                ('wifipassword', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
