# Generated by Django 2.2.7 on 2020-03-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_auto_20200317_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pos',
            name='id',
        ),
        migrations.AlterField(
            model_name='pos',
            name='p_id',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
